// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../objectbox/entities/element_data.dart';
import '../objectbox/entities/mushaf_data.dart';
import '../objectbox/entities/settings.dart';
import '../objectbox/entities/user.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5695174526205380813),
    name: 'User',
    lastPropertyId: const obx_int.IdUid(4, 8596584169510785488),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8121097046250963357),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4575814678754092301),
        name: 'username',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3143501386793757011),
        name: 'settingsId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 8369541278899629778),
        relationField: 'settings',
        relationTarget: 'UserSettings',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8596584169510785488),
        name: 'mushafDataId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 7746610485079453983),
        relationField: 'mushafData',
        relationTarget: 'UserMushafData',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 108559218551549558),
    name: 'UserSettings',
    lastPropertyId: const obx_int.IdUid(7, 5368749521206539205),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 885861951606407149),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8287596272645041452),
        name: 'initPage',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5368749521206539205),
        name: 'updatedAt',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 5158204488349438991),
    name: 'UserMushafData',
    lastPropertyId: const obx_int.IdUid(2, 486392625489474937),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8077524744268339072),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 486392625489474937),
        name: 'updatedAt',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 1867234926092955552),
        name: 'elementData',
        targetId: const obx_int.IdUid(5, 7498263474056846663),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 7498263474056846663),
    name: 'ElementData',
    lastPropertyId: const obx_int.IdUid(6, 5794467697471834517),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5364272024075805505),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4310841449428069570),
        name: 'key',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(3, 3535139043750553455),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 102739221113859876),
        name: 'annotation',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3820782552421138780),
        name: 'markId',
        type: 2,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1143108290443860278),
        name: 'highlightId',
        type: 2,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5794467697471834517),
        name: 'mushafDataId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(4, 4480574627615894053),
        relationField: 'mushafData',
        relationTarget: 'UserMushafData',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(5, 7498263474056846663),
    lastIndexId: const obx_int.IdUid(4, 4480574627615894053),
    lastRelationId: const obx_int.IdUid(1, 1867234926092955552),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [4114569898738216993],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      4583387695649205848,
      472877644037413990,
      6511620712832946713,
      6403158308633255672,
      3762552592680785411,
      1382199870235660840,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    User: obx_int.EntityDefinition<User>(
      model: _entities[0],
      toOneRelations: (User object) => [object.settings, object.mushafData],
      toManyRelations: (User object) => {},
      getId: (User object) => object.id,
      setId: (User object, int id) {
        object.id = id;
      },
      objectToFB: (User object, fb.Builder fbb) {
        final usernameOffset = fbb.writeString(object.username);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, usernameOffset);
        fbb.addInt64(2, object.settings.targetId);
        fbb.addInt64(3, object.mushafData.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final usernameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final object = User(username: usernameParam)
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.settings.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.settings.attach(store);
        object.mushafData.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        object.mushafData.attach(store);
        return object;
      },
    ),
    UserSettings: obx_int.EntityDefinition<UserSettings>(
      model: _entities[1],
      toOneRelations: (UserSettings object) => [],
      toManyRelations: (UserSettings object) => {},
      getId: (UserSettings object) => object.id,
      setId: (UserSettings object, int id) {
        object.id = id;
      },
      objectToFB: (UserSettings object, fb.Builder fbb) {
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.initPage);
        fbb.addInt64(6, object.updatedAt);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final initPageParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final updatedAtParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final object = UserSettings(
          initPage: initPageParam,
          updatedAt: updatedAtParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    UserMushafData: obx_int.EntityDefinition<UserMushafData>(
      model: _entities[2],
      toOneRelations: (UserMushafData object) => [],
      toManyRelations: (UserMushafData object) => {
        obx_int.RelInfo<UserMushafData>.toMany(1, object.id):
            object.elementData,
      },
      getId: (UserMushafData object) => object.id,
      setId: (UserMushafData object, int id) {
        object.id = id;
      },
      objectToFB: (UserMushafData object, fb.Builder fbb) {
        fbb.startTable(3);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.updatedAt);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final updatedAtParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final object = UserMushafData(updatedAt: updatedAtParam)
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        obx_int.InternalToManyAccess.setRelInfo<UserMushafData>(
          object.elementData,
          store,
          obx_int.RelInfo<UserMushafData>.toMany(1, object.id),
        );
        return object;
      },
    ),
    ElementData: obx_int.EntityDefinition<ElementData>(
      model: _entities[3],
      toOneRelations: (ElementData object) => [object.mushafData],
      toManyRelations: (ElementData object) => {},
      getId: (ElementData object) => object.id,
      setId: (ElementData object, int id) {
        object.id = id;
      },
      objectToFB: (ElementData object, fb.Builder fbb) {
        final keyOffset = fbb.writeString(object.key);
        final annotationOffset = object.annotation == null
            ? null
            : fbb.writeString(object.annotation!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, keyOffset);
        fbb.addOffset(2, annotationOffset);
        fbb.addInt8(3, object.markId);
        fbb.addInt8(4, object.highlightId);
        fbb.addInt64(5, object.mushafData.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final keyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final annotationParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final object = ElementData(key: keyParam, annotation: annotationParam)
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..markId = const fb.Int8Reader().vTableGet(buffer, rootOffset, 10, 0)
          ..highlightId = const fb.Int8Reader().vTableGet(
            buffer,
            rootOffset,
            12,
            0,
          );
        object.mushafData.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        object.mushafData.attach(store);
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [User] entity fields to define ObjectBox queries.
class User_ {
  /// See [User.id].
  static final id = obx.QueryIntegerProperty<User>(_entities[0].properties[0]);

  /// See [User.username].
  static final username = obx.QueryStringProperty<User>(
    _entities[0].properties[1],
  );

  /// See [User.settings].
  static final settings = obx.QueryRelationToOne<User, UserSettings>(
    _entities[0].properties[2],
  );

  /// See [User.mushafData].
  static final mushafData = obx.QueryRelationToOne<User, UserMushafData>(
    _entities[0].properties[3],
  );
}

/// [UserSettings] entity fields to define ObjectBox queries.
class UserSettings_ {
  /// See [UserSettings.id].
  static final id = obx.QueryIntegerProperty<UserSettings>(
    _entities[1].properties[0],
  );

  /// See [UserSettings.initPage].
  static final initPage = obx.QueryIntegerProperty<UserSettings>(
    _entities[1].properties[1],
  );

  /// See [UserSettings.updatedAt].
  static final updatedAt = obx.QueryIntegerProperty<UserSettings>(
    _entities[1].properties[2],
  );
}

/// [UserMushafData] entity fields to define ObjectBox queries.
class UserMushafData_ {
  /// See [UserMushafData.id].
  static final id = obx.QueryIntegerProperty<UserMushafData>(
    _entities[2].properties[0],
  );

  /// See [UserMushafData.updatedAt].
  static final updatedAt = obx.QueryIntegerProperty<UserMushafData>(
    _entities[2].properties[1],
  );

  /// see [UserMushafData.elementData]
  static final elementData =
      obx.QueryRelationToMany<UserMushafData, ElementData>(
        _entities[2].relations[0],
      );
}

/// [ElementData] entity fields to define ObjectBox queries.
class ElementData_ {
  /// See [ElementData.id].
  static final id = obx.QueryIntegerProperty<ElementData>(
    _entities[3].properties[0],
  );

  /// See [ElementData.key].
  static final key = obx.QueryStringProperty<ElementData>(
    _entities[3].properties[1],
  );

  /// See [ElementData.annotation].
  static final annotation = obx.QueryStringProperty<ElementData>(
    _entities[3].properties[2],
  );

  /// See [ElementData.markId].
  static final markId = obx.QueryIntegerProperty<ElementData>(
    _entities[3].properties[3],
  );

  /// See [ElementData.highlightId].
  static final highlightId = obx.QueryIntegerProperty<ElementData>(
    _entities[3].properties[4],
  );

  /// See [ElementData.mushafData].
  static final mushafData = obx.QueryRelationToOne<ElementData, UserMushafData>(
    _entities[3].properties[5],
  );
}
