// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../objectbox/entities/user.dart';
import '../objectbox/entities/user_settings.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5695174526205380813),
    name: 'User',
    lastPropertyId: const obx_int.IdUid(3, 3143501386793757011),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8121097046250963357),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4575814678754092301),
        name: 'username',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3143501386793757011),
        name: 'settingsId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 8369541278899629778),
        relationField: 'settings',
        relationTarget: 'UserSettings',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 108559218551549558),
    name: 'UserSettings',
    lastPropertyId: const obx_int.IdUid(7, 5368749521206539205),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 885861951606407149),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8287596272645041452),
        name: 'initPage',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5368749521206539205),
        name: 'updatedAt',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 4114569898738216993),
    lastIndexId: const obx_int.IdUid(1, 8369541278899629778),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [4114569898738216993],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      4583387695649205848,
      472877644037413990,
      6511620712832946713,
      6403158308633255672,
      3762552592680785411,
      1382199870235660840,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    User: obx_int.EntityDefinition<User>(
      model: _entities[0],
      toOneRelations: (User object) => [object.settings],
      toManyRelations: (User object) => {},
      getId: (User object) => object.id,
      setId: (User object, int id) {
        object.id = id;
      },
      objectToFB: (User object, fb.Builder fbb) {
        final usernameOffset = fbb.writeString(object.username);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, usernameOffset);
        fbb.addInt64(2, object.settings.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final usernameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final object = User(username: usernameParam)
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.settings.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.settings.attach(store);
        return object;
      },
    ),
    UserSettings: obx_int.EntityDefinition<UserSettings>(
      model: _entities[1],
      toOneRelations: (UserSettings object) => [],
      toManyRelations: (UserSettings object) => {},
      getId: (UserSettings object) => object.id,
      setId: (UserSettings object, int id) {
        object.id = id;
      },
      objectToFB: (UserSettings object, fb.Builder fbb) {
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.initPage);
        fbb.addInt64(6, object.updatedAt);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = UserSettings()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..initPage = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            6,
            0,
          )
          ..updatedAt = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            16,
            0,
          );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [User] entity fields to define ObjectBox queries.
class User_ {
  /// See [User.id].
  static final id = obx.QueryIntegerProperty<User>(_entities[0].properties[0]);

  /// See [User.username].
  static final username = obx.QueryStringProperty<User>(
    _entities[0].properties[1],
  );

  /// See [User.settings].
  static final settings = obx.QueryRelationToOne<User, UserSettings>(
    _entities[0].properties[2],
  );
}

/// [UserSettings] entity fields to define ObjectBox queries.
class UserSettings_ {
  /// See [UserSettings.id].
  static final id = obx.QueryIntegerProperty<UserSettings>(
    _entities[1].properties[0],
  );

  /// See [UserSettings.initPage].
  static final initPage = obx.QueryIntegerProperty<UserSettings>(
    _entities[1].properties[1],
  );

  /// See [UserSettings.updatedAt].
  static final updatedAt = obx.QueryIntegerProperty<UserSettings>(
    _entities[1].properties[2],
  );
}
